### ISSUE TITLE
Reproduce KGAT

### ISSUE THREAD

**Issue by seelenbrecher** [thunlp/KernelGAT#26]
Hi,

for KGAT, can we reproduce the exact same results as mentioned in the paper?
I run the training script, and got around 77 (lowest was 77.05) for LA on the eval set (run eval.sh), while in the paper, you could achieve 78.05.

Thanks

**Comment by EdwardZH** [comment]
We provide all checkpoints in our open source codes. You should initial your start BERT base checkpoint with our BERT-base retrieval models, and you will get a higher score. For RoBERTa large, you can get better results than the paper reported.

**Comment by seelenbrecher** [comment]
Hi,

I used the same setting as your script.

```
--bert_pretrain ../bert_base \
--postpretrain ../pretrain/save_model/model.best.pt
```

I also downloaded all the checkpoints from here https://thunlp.oss-cn-qingdao.aliyuncs.com/KernelGAT/FEVER/KernelGAT.zip

and I also notice that running the same scripts does not guarantee the same results (the gap is noticeable. sometimes I got 77.0, and sometimes got 77.2)

did I miss something to make it more robust?

**Comment by EdwardZH** [comment]
You can use our supplied checkpoint of KGAT, the same result you can get. The little difference in model performance is acceptable because the random initialization is different. I think you can modify the codes to match the latest BERT model because different versions of hugginface's transformers will influent the model result. In addition, some work has reimplemented our work and achieves 77.8 LA in their paper. I think this paper will soon be published.

**Comment by EdwardZH** [comment]
The optimizer should also be changed if you use the latest transformers package.
